### PR TITLE
Daniel's papers and talks

### PR DESCRIPTION
**Pull request by danper**
Added talks and papers. Also removed all the ST tags on my publications and papers. I really don't like when talks and papers are divided like that and I don't think string theory is a good tag. I will change this eventually but for now I have removed them.

Now added more papers and a news entry. Somehow I didn't get the paper link to work in the news post.

### CODE REVIEW

**Comment by JanEGerken** [comment]
Thanks for your updates, Daniel!
Without any tags, the publications will all appear on the central group page. So once @PhilippMisofCH has converted the selection to a white-list, you could create new tags which you find more meaningful and then those would all get filtered away. On your personal page, all publications would then appear under one heading and show the tags you created.

**Comment by danper** [comment]
Ok, understood!

**Comment by PhilippMisofCH** [comment]
> Thanks for your updates, Daniel! Without any tags, the publications will all appear on the central group page. So once @PhilippMisofCH has converted the selection to a white-list, you could create new tags which you find more meaningful and then those would all get filtered away. On your personal page, all publications would then appear under one heading and show the tags you created.

Should be handled by #12

**Comment by JanEGerken** [comment]
I’ve now merged your updates into the main branch, Daniel. Since Philipp has implemented the white-list for the central publication list, you can create new tags with meaningful names in `_data/tags.yml` and use them for your papers and talks. I’ve removed the "string theory" publications and talks lists, so until we have more fine-grained control over the headlines, it’ll all be in two lists (for publications and talks) on the group member pages.

**Pull request merged**
