### PR TITLE
Changed sorting for upcoming talks and added links to publications and other output

### PR DESCRIPTION
**Pull request by PhilippMisofCH**

### CODE REVIEW

**Comment by PhilippMisofCH** [comment]
Thanks for the feedback! This seems to be a classic case of *works on my machine*
image
I'll investigate it. May I ask which browser and the corresponding version you are using?

**Comment by PhilippMisofCH** [comment]
I also tested with firefox and chromium and both yield the expected results for me...

The error you mentioned is not related to it but I've fixed it (temporarily) anyway now.

Could you check if the console in your browser generates any error messages when reloading the seminar page? For this, open the *inspect* tool and choose the *Console* tab.

**Comment by JanEGerken** [comment]
Okay, in Chromium and Firefox, it actually works, I checked the wrong page before. The error persists in Brave which is based on Chromium. There were three messages in the console:
```
seminar.html:5 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ seminar.html:5
seminar.html:5 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ seminar.html:5
seminar.html:5 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ seminar.html:5
```

**Comment by PhilippMisofCH** [comment]
Ok, that narrows it down a bit. I installed Brave now myself and tested it out but still cannot reproduce the error. Just to be sure that this error persists, can you check again after cleaning the cache of your browser? Because I have to do that quite regularly to test my changes in the javascript files.

**Comment by JanEGerken** [comment]
Okay, that was the problem. After clearing the cache, it worked, perfect!

**Pull request merged**
